#!/usr/bin/env python

import cv2

from ar_markers.hamming.detect import detect_markers

if __name__ == '__main__':
    capture = cv2.VideoCapture(0)

    if capture.isOpened(): # try to get the first frame
        frame_captured, frame = capture.read()
    else:
        frame_captured = False
    while frame_captured:
        markers = detect_markers(frame)
        for marker in markers:
            marker.highlite_marker(frame)
        frame = cv2.putText(frame,str(len(markers)) + " detected markers",(10,30),cv2.FONT_HERSHEY_SIMPLEX,\
	    0.5, (10,10,10),1,cv2.LINE_AA)
        h, w, _ = frame.shape
        
        frame = cv2.putText(frame,"Size"+ str(h) + "x" + str(w),(10,60),cv2.FONT_HERSHEY_SIMPLEX,\
	    0.5, (10,10,10),1,cv2.LINE_AA)
        cv2.imshow('Test Frame', frame)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
        frame_captured, frame = capture.read()

    # When everything done, release the capture
    capture.release()
    cv2.destroyAllWindows()
